schema_type: dataframe
version: 0.20.4
columns:
  RIDAGEYR:
    title: null
    description: null
    dtype: int64
    nullable: true
    checks:
      greater_than_or_equal_to: 25.0
      less_than_or_equal_to: 80.0
    unique: false
    coerce: true
    required: true
    regex: false
  BMXWAIST:
    title: null
    description: null
    dtype: float64
    nullable: true
    checks:
      greater_than_or_equal_to: 85.0
      less_than_or_equal_to: 110.0
    unique: false
    coerce: true
    required: true
    regex: false
  BMXHT:
    title: null
    description: null
    dtype: int64
    nullable: true
    checks:
      greater_than_or_equal_to: 0.0
      less_than_or_equal_to: 175.0
    unique: false
    coerce: true
    required: true
    regex: false
  systolic_bp:
    title: null
    description: null
    dtype: float64
    nullable: true
    checks:
      greater_than_or_equal_to: 120.0
      less_than_or_equal_to: 140.0
    unique: false
    coerce: true
    required: true
    regex: false
  diastolic_bp:
    title: null
    description: null
    dtype: int64
    nullable: true
    checks:
      greater_than_or_equal_to: 75.0
      less_than_or_equal_to: 90.0
    unique: false
    coerce: true
    required: true
    regex: false
  is_female:
    title: null
    description: null
    dtype: int64
    nullable: true
    checks:
      greater_than_or_equal_to: 0.0
      less_than_or_equal_to: 1.0
    unique: false
    coerce: true
    required: true
    regex: false
  told_high_bp:
    title: null
    description: null
    dtype: float64
    nullable: true
    checks:
      greater_than_or_equal_to: 0.0
      less_than_or_equal_to: 1.0
    unique: false
    coerce: true
    required: true
    regex: false
  told_high_cholesterol:
    title: null
    description: null
    dtype: float64
    nullable: true
    checks:
      greater_than_or_equal_to: 0.0
      less_than_or_equal_to: 1.0
    unique: false
    coerce: true
    required: true
    regex: false
  drinking_frequency:
    title: null
    description: null
    dtype: float64
    nullable: true
    checks:
      greater_than_or_equal_to: 0.0
      less_than_or_equal_to: 3.0
    unique: false
    coerce: true
    required: true
    regex: false
  education_level:
    title: null
    description: null
    dtype: float64
    nullable: true
    checks:
      greater_than_or_equal_to: 2.0
      less_than_or_equal_to: 5.0
    unique: false
    coerce: true
    required: true
    regex: false
  phq9_score:
    title: null
    description: null
    dtype: int64
    nullable: true
    checks:
      greater_than_or_equal_to: 1.0
      less_than_or_equal_to: 8.0
    unique: false
    coerce: true
    required: true
    regex: false
  vigorous_minutes_per_week:
    title: null
    description: null
    dtype: float64
    nullable: true
    checks:
      greater_than_or_equal_to: 0.0
      less_than_or_equal_to: 120.0
    unique: false
    coerce: true
    required: true
    regex: false
checks: null
index:
- title: null
  description: null
  dtype: int64
  nullable: false
  checks:
    greater_than_or_equal_to: 0.0
    less_than_or_equal_to: 4.0
  name: null
  unique: false
  coerce: false
dtype: null
coerce: true
strict: true
name: null
ordered: false
unique: null
report_duplicates: all
unique_column_names: false
add_missing_columns: false
title: null
description: null
